from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

def add(_x: int, _y: int) -> int: ...
def subtract(_x: int, _y: int) -> int: ...
def matrix(_x: int) -> NDArray[np.float64]: ...
