name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install conda
        uses: "conda-incubator/setup-miniconda@v2"
        with:
          auto-update-conda: true
          python-version: 3.11
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install Eigen from conda
        run: mamba install eigen

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage manual --all-files

      - name: Run PyLint
        run: |
          echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
          pipx run nox -s pylint

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

        include:
          - python-version: pypy-3.9
            runs-on: ubuntu-latest

    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install conda
        uses: "conda-incubator/setup-miniconda@v2"
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install Eigen from conda
        run: mamba install eigen

      - name: Install package
        run: python -m pip install .[test]

      - name: Test package
        run:
          python -m pytest -ra --cov --cov-report=xml --cov-report=term
          --durations=20

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.4
